### ISSUE TITLE
Add Documentation for Microphone

### ISSUE THREAD

**Issue by DJLevel3** [jameshball/osci-render#109]
# Add Documentation for Microphone
### Issue
Documentation for the microphone option is nonexistent, but if it does what I think it is supposed to do then it would be extremely useful.

It may not be working for me, but I'm not 100% sure since I don't know what it's actually supposed to do.

### Fix
Add documentation

**Comment by DJLevel3** [comment]
So, the mic doesn't do what I thought it did. Oh, well, I guess I'll have to write a Lua script for it ;)

**Comment by jameshball** [comment]
What did you expect it to do? Very happy to add whatever you're trying to replicate in lua :) it would also be good to add the mic value to lua as a variable so that you can use it there rather than through a slider

**Comment by DJLevel3** [comment]
When rendering a shape, the synth loops through a set of sample points one by one, and if you think of it like linear interpolation it's like a saw wave from the start to the end. I expected it to replace that saw wave with the mic input, which lets you put a voice or a sound effect in the shape. See Curse of the Pharaoh by Chris Allen for lots of examples.

**Comment by DJLevel3** [comment]
Or like this
https://youtu.be/YyP5Ri4NXtg

**Comment by jameshball** [comment]
Ooo that would be awesome to implement! So if you have mic samples ranging from -1 to 1, you just map this to the x/y of the image you want to draw where 1 is one end of the draw path and -1 is the other end?

This shouldn't be that hard to implement but might take a bit of thought to optimise it so that it doesn't have to loop through all of the path every time we want to find the position to draw next.

**Comment by jameshball** [comment]
Just an aside: planning to write fairly extensive user documentation for all of osci-render over the coming weeks - would be great to pass some drafts of this past you if possible!

**Comment by DJLevel3** [comment]
100%! I'd love to help out!

**Comment by jameshball** [comment]
Currently tracking this here https://github.com/jameshball/osci-render/wiki/User-Documentation

**Comment by jameshball** [comment]
https://github.com/jameshball/osci-render/wiki#microphone-input Closing this issue now as I've now added documentation here :)

The rest of this documentation is probably around 80% done!
