### ISSUE TITLE
Remove Controls from menu bar and prevent translation from being controlled by scroll bar

### ISSUE THREAD

**Issue by jameshball** [jameshball/osci-render#111]
Since the scrollable menu for Effects was added, it no longer makes sense to control the translation text boxes by scrolling as it moves the scrollable menu at the same time.

This should be disabled and the Controls sub-menu should be removed from the menu bar as a result.

If anybody wants to work on this, the Controls menu is located in `main.fxml` and `MainController.java`, and the Translation effect text fields are located in `EffectsController.java`.

![image](https://user-images.githubusercontent.com/38670946/186602745-45f0c1fb-08bb-4962-9457-f77049dffb2a.png)

**Comment by Kar-3kn** [comment]
Hi I have made the changes and made a pull request

**Comment by jameshball** [comment]
Fixed by #112
