### ISSUE TITLE
Lua Audio Effects

### ISSUE THREAD

**Issue by DJLevel3** [jameshball/osci-render#133]
Hello! I have a cool idea of a feature for osci-render, but from what I can tell it's not possible to do what I want to with Lua at the moment. I basically want to use osci-render's built-in rendering functions from Lua, but with control over the frequency and phase that they render with.

I'm going to look at implementing it myself, so we'll see how that goes, but if I can't do it then I'd like some help. Thanks!

**Comment by jameshball** [comment]
That's a great idea! Do you mean being able to access the value of the frequency slider from within a Lua script or automatically changing the frequency coming out of Lua? Completely agree that having frequency values within Lua would be super valuable and make it quite easy to make frequency-based visuals in Lua!

**Comment by DJLevel3** [comment]
My plan was to add a way to run the main rendering function inside Lua as functions so effects can affect all aspects of osci-render.

I was thinking a set like:
- `getRender()`
- `getNextRender(frequency)`
- `getDeltaRender(delta_t)`
- `getAbsoluteRender(absolute_t)`

This would mean that you can get the render as it would normally be or with lower-level control as needed.

**Comment by DJLevel3** [comment]
To be clear, this is not finalized and I haven't yet made any code. I'm about to do so now.

**Comment by DJLevel3** [comment]
Alternately, I could use a set of control functions and only one getter.

Something like:
- `setPhase(phase)`
- `setFrequency(frequency)`
- `setDelta(delta)` (1/frequency)
- (getters for all of the above, e.g. getPhase())
- `getNextSample()` (advances by one sample and renders)

**Comment by jameshball** [comment]
Ah I see so you're basically thinking of a few functions to expose low-level details about what osci-render is doing? Things like the drawing path, or the shapes that are being drawn, the next samples that are being drawn etc.?

**Comment by DJLevel3** [comment]
Exactly. I basically want to be able to make audio effects for objects and Blender animations that osci-render is rendering.

**Comment by jameshball** [comment]
In that case...... You might be able to do this in the 3D perspective effect? If you don't change the z axis at all, you can apply audio effects to just the X and y channels. I'm gonna support this properly outside of the vector cancelling effect soon with its own slider etc.

If this isn't what you need for what you want to do then ignore me!

**Comment by DJLevel3** [comment]
I mean custom Lua audio effects including stuff with frequency sweeps, vibrato, and things like that. But thanks for reminding me of the ones that are available!

**Comment by DJLevel3** [comment]
Well, this'll probably take at least a few days to do, as I'm going to make some pretty big changes. Basically, I want to rearchitect the Lua implementation so it is an entirely separate pipeline from the normal audio pipeline.

When the Lua pipeline is enabled, it will change the behavior of `ShapeAudioPlayer`'s `generateChannels()` so that it calls the Lua script before the effects rather than the `SampleSource`, and then the Lua script can call the `SampleSource` at its own discretion. I'm probably going to rewrite `generateChannels()` entirely and generalize many parts of it so that similar changes can be easily made down the line in other areas if needed.

The UI will need to be modified, which I have absolutely no idea how to do, but I'll get help with that when I need it.

**Comment by jameshball** [comment]
This makes sense! One thing to consider is that the performance of running lua scripts is okay but not amazing, so it might be expensive to run it every single sample regardless of whether a Lua script is open or not. Either way we can tackle that hurdle when it comes to it!

**Comment by DJLevel3** [comment]
Yeah, the Lua script pipeline will only run if a script is loaded and
enabled for performance reasons.

**Comment by DJLevel3** [comment]
Well, I ran `git pull` without committing and pushing changes first, so I have just lost about 90% of my progress. As of now, this idea is on hold while I work on easier improvements like the frame baking issue I opened a while ago. Closing as not planned for now until I get back to it.

**Comment by DJLevel3** [comment]
More accurately, I'm going to do frame baking with a new issue. I misremembered what the other issue was about lol
