### ISSUE TITLE
Running multiple instances of osci-render simultaneously

### ISSUE THREAD

**Issue by foxpup** [jameshball/osci-render#161]
FEATURE REQUEST: In order to play around with this art form I went hunting for vectorscopes and snagged a total of three Tectronix 603/604 XYZ units.  Two of them came as left and right halves of a rack-mount setup and I have placed prominently above my main monitor for display enjoyment.  I can install as many sound-cards as I like in my computer and hook them up to the units, but when I try to run multiple instances of the program things get a bit unreliable.  Perhaps it was never intended to be treated that way.  It sure would be cool if it could be. :-)

Running one instance sure works nicely sending audio to whichever vectorscope I select so my hardware seems just fine. :-)

**Comment by jameshball** [comment]
Thanks for raising an issue! That sounds like a good idea :) in theory it should be fine with multiple instances and I've tested it a little bit but not as much as you're describing. What happens to the audio/program when things come unreliable? Is is just general stuttering?

I wonder if you get less stuttering if you reduce the sample rate of your audio devices from within osci-render?

**Comment by foxpup** [comment]
If you are wondering, I'll gather some more info with my setup and post it here. (with an emphasis on your specific inquiries :-) )  What I can say right not is that most to my trouble involved one of the apps becomining completely unresponsive to the point where I had to end-task it, while the other one stayed working.  Again, if it interests you, I'll try to gather better details. :-)

**Comment by jameshball** [comment]
Ah I see thanks! Some extra details would be very helpful, thank you :)

**Comment by foxpup** [comment]
> Ah I see thanks! Some extra details would be very helpful, thank you :)

Well I started my system up trying to replicate the problem and it just plain worked as I had it set up.  In my setup I had copied the install folder to another I called osci-render-2 and made a shortcut to the executable there and that seems to work.  I should try again but last time I tried to run two instances by just klicking on the launcher twice I only got one insantance.  This is a windoze install even though I prefer linux.  I'm sure to be playing with that environment soon enough.  Amazingly the setup even works using only ONE sound card.  Apparently the headphones port on the chassis and the speaker port on the back are sufficiently independent to work that way. :-)  It should be noted that it seems I'm getting a lot more bandwidth out of the speaker port than the headphones jack (both at max ~190k stereo sample rate)  I plan to play around with diferent sound cards, maybe even USB ones.  We'll se what works.  Again I'll post what I discover and think is worth sharing here.  I even made a YouTube video illustrating the success.  This is pretty fun, but I think the real fun will begin when I start plaing with LUA. :-)
 https://youtu.be/wkthCBeVqW8
 LLAP

**Comment by jameshball** [comment]
This is so cool!! Really happy to hear it's working now :) Btw the sample rate in osci-render is a bit misleading - even if it's outputting 192khz it is still dependent on your soundcard (even though osci-render does actually process all 192khz!). This means if you have a sound card with a lower sample rate, it's probably best to change osci-render to the same sample rate.

I'm going to close the issue since it seems to be working but please keep replying here or let me know otherwise if you do anything cool with Lua! Have yet to see anyone use it properly yet so would be awesome to see what you come up with :)

**Comment by foxpup** [comment]
LUA seems to be the other of two major ways to be creative here.  3D object design I've already shown.  I really had to reduce the number of nodes in Starbug in my video to make it practical in this context.  That acknowledged, I think the other great domain of creativity is in LUA. It's going to take while for me because it's new, but I think this context should provide a lot of near-immediate feedback to keep me motivated and having fun.  I've been meaning to ask, is there a forum anywhere for discussing and showing off projects?  The github trouble ticket system doesn't seem to be the right place for that. :-)

**Comment by jameshball** [comment]
There's not currently a forum just for osci-render really - I'd say the best place is just on Reddit on r/oscilloscopemusic and just mentioning osci-render in the title or in a comment or something :)
