### ISSUE TITLE
Frame Player Counting Error

### ISSUE THREAD

**Issue by Adlerkampf** [jameshball/osci-render#162]
When opening a folder of for example SVG´s that contains 5000 files that are names "1.svg", "2.svg"... the frame player skips from frame 10 to 100 to 1000 and then starts counting until it tries to reach 1010 but fails and resets to 101 and then continus futher until the 0 accurs at the end of a number 
![Small gif of the bug](https://user-images.githubusercontent.com/51096486/222265234-69a8540b-ffb6-46c8-839c-de1a1539b913.gif)

**Comment by jameshball** [comment]
Ah, that's not ideal! I will try to fix this at some point but for now you could name them like a, b, c, d, ..., z, aa, ab, ac... etc and it should work. Not a good solution though I appreciate! Thanks for raising the issue

**Comment by jameshball** [comment]
https://blog.jooq.org/how-to-order-file-names-semantically-in-java/ leaving this here for future reference as a way this can be fixed

**Comment by jameshball** [comment]
https://blog.jooq.org/how-to-order-file-names-semantically-in-java/ leaving this here for future reference as a way this can be fixed

**Comment by jameshball** [comment]
Not really a supported use-case anymore in osci-render 2 as you can either use Blender or GIFs for animations
