### ISSUE TITLE
osci-render-unix dont work. Unsupported JavaFX configuration, XSetErrorHandler() called with a GDK error trap pushed

### ISSUE THREAD

**Issue by xintrea** [jameshball/osci-render#164]
Hello!

I have Debian Linux Stable 11 with all updates.

I have official Java v.20:

```
> java --version
java 20.0.2 2023-07-18
Java(TM) SE Runtime Environment (build 20.0.2+9-78)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.2+9-78, mixed mode, sharing)
```

I run osci-render with next command:

```
> java "-Dfile.encoding    =UTF8" -jar osci-render-unix-1.33.2.jar
jul. 30, 2023 10:51:41 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6b715c5b'
(java:16882): Gdk-WARNING **: 22:51:45.405: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```

After running, osci-render show interface. But after push to button "Start new proj..." show white screen and do noting. In console log no append warning or error, nothing. And window don't response to window button. Window don't close if push [x]. Only if press Ctrl+C in console, the osci-render is finish work.

How to correct run osci-render?

**Comment by DJLevel3** [comment]
This may be relevant.
https://stackoverflow.com/questions/55446534/how-to-fix-java22494-gdk-warning

**Comment by xintrea** [comment]
> This may be relevant. https://stackoverflow.com/questions/55446534/how-to-fix-java22494-gdk-warning

After append option "-Djdk.gtk.version=2", GTK warning is changed:

```
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6b715c5b'
WARNING: A command line option has enabled the GTK 2 library
WARNING: The JavaFX GTK 2 library is deprecated and will be removed in a future release
```

But behavior don't change. After push to button "Start new proj..." show white screen and do noting.

**Comment by xintrea** [comment]
I found method for run osci-render in Debian Linux 11.

1. Install jackd package.
2. Install official Oracle Java JDK 19 or 20, not OpenJDK
3. Run QJackCtl and push start Jackd
4. Run Java VM with jar-file:

/usr/lib/jvm/jdk-20/bin/java "-Dfile.encoding=UTF8" "-Djdk.gtk.version=2" -jar ./osci-render-unix-1.33.2.jar

5. Press "New proj..." in osci-render. The osci-render is freeze.
6. Stop Jackd in QJackCtl.
7. The osci-render show our work interface.
8. Start Jackd in QJackCtl.

This method from here: https://webhamster.ru/mytetrashare/index/mtb0/16907522569aygrnabey
