### ISSUE TITLE
Why james.ball.sh/oscilloscope don't show default cube?

### ISSUE THREAD

**Issue by xintrea** [jameshball/osci-render#165]
I run osci-render, push "Start new Proj..." and have work interface.
This interface show cube.obj near ChooseFile button.
The netstat utility shows that port 42988 is open.
I open https://james.ball.sh/oscilloscope in Firefox.
The wireshark utility show traffic between local port 42988 and Firefox.

But oscilloscope show only green dot.

Why program oscilloscope don't show default cube?

**Comment by xintrea** [comment]
Finally figured it out.

It turns out that it was impossible to check the **Start muted** checkbox in the initial screen. I thought that with this checkbox, output to a real audio device would simply not occur. But in fact, it turned out that all output sound is turned off, including the data stream to the software oscilloscope.

**Comment by jameshball** [comment]
Ah I'm sorry about this! Glad you figured it out. When you select Start Muted, the volume is set to 0 and you need to increase the volume on the right hand side using the slider. It should all work then :)
