### ISSUE TITLE
Can't seem to use the microphone function / None of my audio input devices seem to work

### ISSUE THREAD

**Issue by crisse19** [jameshball/osci-render#166]
macOS Ventura 13.3.1 (a)

Love this tool! I was looking to use it with my mic and/or route audio through it when I discovered that none of my input devices seem to do anything. 

Mic volume is up
My input devices works fine when i test them in the general settings on my computer and in my DAW (Ableton Live 11) 

I've tried every device and its variance in the audio input device menu, sometimes switching between them makes it crash.

**Comment by jameshball** [comment]
Closing this as I've just released osci-render 2.0 which is a complete rewrite of osci-render from scratch and should solve this problem! You can get it [here](https://osci-render.com) :)
