### ISSUE TITLE
Where can I read about osci-render control via MIDI?  How do I switch a file for rendering using MIDI?

### ISSUE THREAD

**Issue by xintrea** [jameshball/osci-render#168]
In official wiki the MIDI control paragraph is empty.

How do I switch a file for rendering using MIDI, just like the J and K keys do?

**Comment by jameshball** [comment]
Sorry about that! You can send program change messages to change what file is currently being rendered: https://www.recordingblogs.com/wiki/midi-program-change-message

Basically, this works by sending the program number of the file you want to change to, so 1 would be the first file you opened, 2 is the second, etc.

I explain MIDI control in more detail in this video: https://youtu.be/PKVCx7rs_r8

Let me know if you have any more questions!

**Comment by xintrea** [comment]
> Basically, this works by sending the program number of the file you want to change to, so 1 would be the first file you opened, 2 is the second, etc.

According to the MIDI specification, it turns out that only 128 files can be used?

**Comment by jameshball** [comment]
Yes, due to MIDI limitations only 128 files can be used.

You need to send MIDI CC messages to control the sliders in osci-render by first clicking the MIDI button next to the slider and then sending the CC message to the channel you want to associate it. That pairs it with that CC channel and any further CC messages are used to change the value of the slider.

**Comment by xintrea** [comment]
> ... by first clicking the MIDI button next to the slider and then sending the CC message to the channel you want to associate it. That pairs it with that CC channel and any further CC messages are used to change the value of the slider.

It is interactive communication for one controller. But how to assign some MIDI (volume or other) controllers with some osci-render sliders? It is possible?

**Comment by xintrea** [comment]
> Yes, due to MIDI limitations only 128 files can be used.

Anyway, thanks You to your OpenSource project. 

The oscilloscope demo "Pittone" for Undefined 2023 demoparty created with your Osci-Render + SunVox and Audacity:

https://www.youtube.com/watch?v=InP7aPsw48s

Prods page (with source): https://events.retroscene.org/undefined2023/wild

**Comment by jameshball** [comment]
That's awesome thank you for sharing! I'll close this for now but please just reopen if you have more questions :)
