### ISSUE TITLE
Linux compilation instructions???

### ISSUE THREAD

**Issue by reahari** [jameshball/osci-render#174]
Congratulations on the rewrite and new release!

Are there instructions for compiling the vst on Linux?

**Comment by jameshball** [comment]
I'm gonna figure this out later today, but the short answer is that it should be very easy by downloading JUCE and then opening the Projucer project file and exporting the makefile. There's some good instructions here: https://forum.juce.com/t/getting-started-on-ubuntu/47209

Nothing in principle stopping this from being possible though!

**Comment by jameshball** [comment]
Added compilation instructions to the end of the README, and also added Linux binaries (standalone + VST3) to https://osci-render.com/

Please reopen if it doesn't work!
