### ISSUE TITLE
Paying some money  : not possible (in Germany, no credit card)

### ISSUE THREAD

**Issue by shivahoj** [jameshball/osci-render#198]
Hello,
 I would have loved to pay some money, but ApplePay wouldn't let me("this payment method is not available in Your country" or something, although I pay at the local supermarket with my iPhone every day), and I have no credit card. 
So I had to download it without paying for it, just wanted to let You know...
Maybe You could add PayPal?

**Comment by jameshball** [comment]
Hi, thanks so much! You can also send a donation to my PayPal here http://paypal.me/jameshball or on GitHub sponsors https://github.com/sponsors/jameshball
