### ISSUE TITLE
Cant get it to work. Theres no sound.

### ISSUE THREAD

**Issue by HenryKleinschmidt** [jameshball/osci-render#25]
Hello. I just stumbled upon this software and was so excited to check it out. But sadly it doesn't work on my Systems or I haven't figured out how to use it. When I select an .obj file nothing happens and when I hit record it always creates a file that is 44 bytes in size
![oscirender](https://user-images.githubusercontent.com/53699624/119846352-59acb100-bf0a-11eb-9c2f-35402383af43.png)
![properties](https://user-images.githubusercontent.com/53699624/119846481-76e17f80-bf0a-11eb-922c-7cd4cd1db066.png)

**Comment by jameshball** [comment]
Hi, thanks for creating an issue.

Is there any sound when you first open the program?

Also, can you send me a screenshot of your audio devices like below:
![image](https://user-images.githubusercontent.com/38670946/119847091-97a5d700-bf02-11eb-9c3a-d2feae6e3205.png)
You can find this by right-clicking the speaker in your taskbar and clicking Sounds:
![image](https://user-images.githubusercontent.com/38670946/119847473-e94e6180-bf02-11eb-843c-38ad3062abe7.png)

And can you send a screenshot of the advanced tab on 'Properties when you right click your default audio device like below:
![image](https://user-images.githubusercontent.com/38670946/119847246-ba37f000-bf02-11eb-90c3-2c2f2d7f2de2.png)

Thanks very much!

**Comment by HenryKleinschmidt** [comment]
Thanks for the fast response! There's no sound when I start the program and the "L/R Frequency" Display is empty
![sound](https://user-images.githubusercontent.com/53699624/119848572-3551d400-bf0c-11eb-900e-6e0bda005516.png)
![speaker properties](https://user-images.githubusercontent.com/53699624/119848581-371b9780-bf0c-11eb-81a0-260cefa9301a.png)

**Comment by jameshball** [comment]
If there's any way of you testing your other audio devices (setting them as default and re-opening the program) could you try that? If that still doesn't work, could you try again but by disabling all non-used audio devices and only having the one you are using set as default and enabled?

**Comment by HenryKleinschmidt** [comment]
Doesn't work either :/
![disabled](https://user-images.githubusercontent.com/53699624/119850211-9f1ead80-bf0d-11eb-84ae-342781775fcc.png)

**Comment by jameshball** [comment]
Ok thanks, can you please try this release and see if there's any difference? https://github.com/jameshball/osci-render/releases/tag/v1.6.3

**Comment by HenryKleinschmidt** [comment]
Thank you! Now it works
