### ISSUE TITLE
Crash on Linux Mint 21.3 (glibc 2.38 required)

### ISSUE THREAD

**Issue by constance-oq** [jameshball/osci-render#260]
When running the osci-render binary on Mint 21.3 Virginia, it crashes with the following output.
`./osci-render: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.38' not found (required by ./osci-render)`

Mint 21.3 comes with glibc-2.35, which cannot be updated without breaking the operating system.

It's worth noting that JUCE also relies on glibc-2.38.

While this is a dependency issue I believe it's worth raising, as Mint is pretty mainstream as far as Linux goes. Feel free to close if this is outside the scope of development.

**Comment by jameshball** [comment]
Thanks for reporting this issue! To compile or run on Linux, you'll need to use Ubuntu 24.04 or equivalent, such as Mint 22.

Although I make sure that osci-render compiles for Linux, I unfortunately don't have the time or user base to make sure it's well documented or properly supported. I am very open to contributions though if you'd like to improve this!
