### ISSUE TITLE
Some lines in .svg rendering made far too long

### ISSUE THREAD

**Issue by DJLevel3** [jameshball/osci-render#43]
**Describe the bug**
When rendering certain .svg files, lines that should be relatively short are rendered as very long lines.

**To Reproduce**
1. Load [this](https://drive.google.com/drive/folders/1h8neAJr-d3biCFzBmwk2hTsHH8hYA4dM?usp=sharing) folder of .svg images into osci-render
2. Compare output to the images in the folder

**Expected behaviour**
SVG images render with correctly-sized lines and are positioned as they are in the original file

**Screenshots**
Expected images and resultant output are in the linked folder, result is in the out.wav to play back on an oscilloscope

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1.16.3

**Comment by DJLevel3** [comment]
Aside from the long lines, the images are rendering correctly, but I can't center the image in the frame with the long line sticking out the back. The images render correctly in my image viewers so I don't think that the images are a problem.

**Comment by jameshball** [comment]
I also noticed this when I was rendering the example SVG you gave before but was unsure whether it was an issue - thanks for letting me know!
I am planning to have a look at this tomorrow :)

**Comment by DJLevel3** [comment]
I'm looking too, and I noticed that the camera has some zooming and
centering code that might mess things up, so I'm testing some changes to
that, like an 'animation mode' kind of thing that changes some stuff to be
more suitable for animations.

Zach Smartphone :)

**Comment by jameshball** [comment]
A few days ago, I actually looked into that code you were talking about, and found it to be quite messy and incorrect. Particularly Shape.center does not center a shape whatsoever, and only does so if the shape has been 'normalised' as per the Shape.normalize function.

An animation mode sounds sensible - I was also thinking something that lets you control the position of what's being drawn would make a lot of sense too e.g. sliders or input boxes for X/Y translation.

I'm going to have a play around and think about what seems sensible - feel free to open a PR with changes if you find anything that improves it :)

**Comment by jameshball** [comment]
As for the long lines, I suspect this could be an issue with the SVGParser but I'll investigate further

**Comment by jameshball** [comment]
![image](https://user-images.githubusercontent.com/38670946/146974946-be644fa0-7e23-4dbb-9b8c-6fbf14e032fe.png)

Is this what it looks like for you?

**Comment by jameshball** [comment]
https://user-images.githubusercontent.com/38670946/146984766-6c7007cc-5018-431e-af3b-aa44bb424e89.mp4

^ Currently what this looks like (on an imperfect software oscilloscope)

I am now properly using the `viewBox` and `height`/`width` attributes of the SVG so it should properly render :) Making a few more changes and then should be ready to merge

**Comment by DJLevel3** [comment]
Perfect! That's pretty much exactly what it should look like!
