### ISSUE TITLE
rendering issue when visualizing output on a software lissajous

### ISSUE THREAD

**Issue by khimaros** [jameshball/osci-render#51]
**Describe the bug**
i'd like to use osci-render as an input to https://github.com/BespokeSynth/BespokeSynth

however, the image of the cube obj rendered on a lissajous is not quite right.

**To Reproduce**
1. install JACK (or pipewire)
2. launch BespokeSynth
3. configure BespokeSynth audio input as JACK (restart if needed)
4. create an `audio effects` / `input` module
5. create an `audio effects` / `lissajous` module
6. wire the `input` to the `lissajous`
7. launch osci-render
8. open qjackctl / Graph and wire the output of osci-render to the input of BespokeSynth

**Expected behaviour**
i'd expect to see the cube rendered on the software lissajous

**Screenshots**
![Screenshot from 2022-03-15 08-35-14](https://user-images.githubusercontent.com/231498/158414942-e3d23afe-c463-4edc-b3e6-ad335645c6c0.png)

**Desktop (please complete the following information):**
 - OS: `Debian Bookworm`
 - Version: `1.19.2`

**Comment by jameshball** [comment]
Thanks for reporting this! I'll take a look at this on Windows. Is there any chance you could try this out by visualising the output on another software oscilloscope like the ones I've mentioned in the README to try and locate the issue? I would recommend https://dood.al/oscilloscope/ if you can route your mic to it.

**Comment by khimaros** [comment]
@jameshball i was able to route to the microphone to the one you linked and the rendering is also wrong there.

![Screenshot from 2022-03-15 10-13-44](https://user-images.githubusercontent.com/231498/158433847-7d89d8a8-74be-4e4c-b2b3-2f737e240f11.png)

**Comment by khimaros** [comment]
i was able to get it working.

i recorded a 30s sample in osci-render and loaded that into dood.al and it looked fine.

then i tried the same in BespokeSynth and it was still rendering incorrectly.

the fix was disabling `autocorrelation` on the lissajous module and running everything through wireplumber/alsa at 192khz

**Comment by jameshball** [comment]
![image](https://user-images.githubusercontent.com/38670946/158445641-30d00c58-4d65-4d6a-a4ef-342931c0b3a4.png)

I get a similarly distorted image when using BespokeSynth, but unfortunately, I don't think that's an issue on my end. All looks correct when I render it at the same time on my real oscilloscope :)

**Comment by jameshball** [comment]
Disabling autocorrelation didn't make any difference for me 😕

**Comment by khimaros** [comment]
@jameshball i think you want to change the input to `1&2` -- basically, i think this sort of rendering problem indicates a missing stereo channel in pipeline.

**Comment by jameshball** [comment]
Ahhh gotcha, thanks and enjoy using this :)

**Comment by jameshball** [comment]
![image](https://user-images.githubusercontent.com/38670946/158447294-ab36dd76-8c46-4ac4-ae7b-fa239e7b84ed.png)
![image](https://user-images.githubusercontent.com/38670946/158447319-a6a14eb8-cd41-455e-a9a5-24a07ec4afde.png)

You're welcome! Btw just FYI looks like the Y direction is flipped on BespokeSynth

**Comment by khimaros** [comment]
i'll file a bug for that with bespoke.

would flipping x/y in osci-render also be a reasonable feature request?

**Comment by jameshball** [comment]
Yes that's absolutely a reasonable request, I'll add that shortly :)

**Comment by jameshball** [comment]
Released this https://github.com/jameshball/osci-render/releases/tag/v1.19.3 :)

**Comment by khimaros** [comment]
wonderful, thank you!
