### ISSUE TITLE
Add option for 24-bit recording

### ISSUE THREAD

**Issue by DJLevel3** [jameshball/osci-render#83]
I've been using osci-render to make some music, and it's a bit annoying that the recording output can't go higher than 16-bit depth. I think that a 24-bit recording option would be a great addition, and it shouldn't be too hard to implement if I'm interpreting the code right.

On Windows, the Java audio engine used in osci-render doesn't support higher than 16-bit audio, but from what I can tell there's nothing preventing the audio recording from rendering at a different bit depth than the audio output. Therefore, I'm pretty sure that with relatively little modification it should be possible to add a "24-bit recording" toggle to make the output render at high quality.

I'm going to try to program a test for that myself, but I'm not experienced in the GUI side of the programming so I'll need someone more experienced than me to make the toggle part.

**Comment by jameshball** [comment]
Thanks for the feedback! This is a great suggestion and the solution you've suggested should work well - thinking it can be generalised to allow any choice of bit depth with a similar bit of code to below:

https://github.com/jameshball/osci-render/blob/d9cffb0b45fb211b64d0507102230b131fd44a2f/src/main/java/sh/ball/audio/engine/XtAudioEngine.java#L41

I'm happy to work on this later today as I don't think it should be a massive change - thanks for having a look too :)
